    RuleSet = {
    Unit: {
	marine: {
        name: 'Marine',
	    cost: 100,
	    race: 'sapiens',
	    mobility: 9,
	    vision: 4,
	    class: 'GL',
	    attack: { GL: 6, GH: 3, AIR: 3, AQUA: 2},
	    minRange: 1,
	    maxRange: 1,
	    defense: 5,
	    canCapture: true,
	    attackAfterMove: true,
	    moveAfterAttack: 0,
	    repair: 1,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{mountain: [6, 2, 4],
		forest: [4, 2, 3],
		base: [4, 2, 2],
		harbor: [3, 2, 2],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [5, -1, -1],
		bridge: [3, 0, -1],
		road: [3, 0, -1],
		city: [5, -2, -2],
		reef: [6, -2, -3],
		abyss: [6, -3, -4],
		swamp: [6, -1, -2]}
	},
	mecha2: {
        name: 'Mecha 2',
	    cost: 100,
	    race: 'sapiens',
	    cannotBeBuilt: true,
	    mobility: 8,
	    vision: 3,
	    class: 'GL',
	    attack: { GL: 7, GH: 4, AIR: 3, AQUA: 2},
	    minRange: 1,
	    maxRange: 1,
	    defense: 8,
	    canCapture: true,
	    attackAfterMove: true,
	    moveAfterAttack: 0,
	    repair: 1,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{mountain: [6, 2, 4],
		forest: [4, 2, 3],
		base: [4, 2, 2],
		harbor: [3, 2, 2],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [5, -1, -1],
		swamp: [6, -1, -2]}
	},
	engineer: {
            name: 'Engineer',
	    cost: 200,
	    race: 'sapiens',
	    mobility: 6,
	    vision: 3,
	    class: 'GL',
	    attack: { GL: 0, GH: 0, AIR: 0, AQUA: 0},
	    minRange: 0,
	    maxRange: 0,
	    defense: 0,
	    canCapture: true,
	    attackAfterMove: false,
	    moveAfterAttack: 0,
	    repair: 1,
	    repairBonus: 2,
	    actions: 1,
	    unitConversion: ['mecha', 'mecha2'],
	    specialAttack: 'EMP',
	    terrain:
		{mountain: [6, 0, 4],
		forest: [4, 0, 3],
		base: [4, 0, 2],
		harbor: [3, 0, 2],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [5, 0, -1],
		bridge: [3, 0, -1],
		road: [3, 0, -1],
		city: [5, -2, -2],
		reef: [6, -2, -3],
		abyss: [6, -3, -4],
		swamp: [6, 0, -2]}
	},
	marauder: {
            name: 'Marauder',
	    cost: 250,
	    race: 'sapiens',
	    mobility: 12,
	    vision: 5,
	    class: 'GH',
	    attack: { GL: 8, GH: 4, AIR: 4, AQUA: 4},
	    minRange: 1,
	    maxRange: 1,
	    defense: 7,
	    canCapture: false,
	    attackAfterMove: true,
	    moveAfterAttack: 0,
	    repair: 1,
	    repairBonus: 0,
	    actions: 2,
	    terrain:
		{forest: [6, 0, -3],
		base: [4, 0, -1],
		harbor: [3, 0, -1],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [4, 0, 0],
		bridge: [2, 0, -2],
		road: [2, 0, -2],
		city: [5, -3, -3],
		swamp: [6, -1, -2]}
	},
	tank: {
            name: 'Tank',
	    cost: 400,
	    race: 'sapiens',
	    mobility: 8,
	    vision: 3,
	    class: 'GH',
	    attack: { GL: 10, GH: 10, AIR: 0, AQUA: 9},
	    minRange: 1,
	    maxRange: 1,
	    defense: 13,
	    canCapture: false,
	    attackAfterMove: true,
	    moveAfterAttack: 0,
	    repair: 2,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{forest: [6, 0, -3],
		base: [4, 0, -1],
		harbor: [3, 0, -1],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [4, 0, 0],
		bridge: [2, 0, -2],
		road: [2, 0, -2],
		city: [5, -3, -3],
		swamp: [6, -1, -2]}
	},
	helicopter: {
            name: 'Helicopter',
	    cost: 500,
	    race: 'sapiens',
	    mobility: 12,
	    vision: 5,
	    class: 'AIR',
	    attack: { GL: 12, GH: 7, AIR: 9, AQUA: 8},
	    minRange: 1,
	    maxRange: 1,
	    defense: 10,
	    canCapture: false,
	    attackAfterMove: true,
	    moveAfterAttack: 6,
	    repair: 1,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{mountain: [3, 0, 0],
		forest: [3, 0, 0],
		base: [4, 0, 0],
		harbor: [3, 0, 0],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [3, 0, 0],
		bridge: [3, 0, 0],
		road: [3, 0, 0],
		city: [5, -2, -2],
		reef: [3, 0, 0],
		abyss: [4, 0, 0],
		swamp: [3, 0, 0],
		water: [3, 0, 0]}
	},
	battery: {
            name: 'Battery',
	    cost: 650,
	    race: 'sapiens',
	    mobility: 7,
	    vision: 4,
	    class: 'GH',
	    attack: { GL: 12, GH: 10, AIR: 12, AQUA: 10},
	    minRange: 2,
	    maxRange: 4,
	    defense: 4,
	    canCapture: false,
	    attackAfterMove: false,
	    moveAfterAttack: 7,
	    repair: 1,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{forest: [6, 0, -3],
		base: [4, 0, -1],
		harbor: [3, 0, -1],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [4, 0, 0],
		bridge: [2, 0, -2],
		road: [2, 0, -2],
		city: [5, -3, -3],
		swamp: [6, -1, -2]}
	},
	destroyer: {
            name: 'Destroyer',
	    cost: 800,
	    race: 'sapiens',
	    mobility: 12,
	    vision: 5,
	    class: 'AQUA',
	    attack: { GL: 10, GH: 10, AIR: 12, AQUA: 16},
	    minRange: 1,
	    maxRange: 3,
	    defense: 12,
	    canCapture: false,
	    attackAfterMove: true,
	    moveAfterAttack: 0,
	    repair: 2,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{water: [3, 0, 0],
		bridge: [4, 0, -2],
		reef: [5, -3, -4],
		ocean: [3, 0, 0],
		harbor: [3, 0, -1]}
	},
	mecha: {
            name: 'Mecha',
	    cost: 100,
	    race: 'titans',
	    mobility: 7,
	    vision: 4,
	    class: 'GL',
	    attack: { GL: 6, GH: 3, AIR: 4, AQUA: 2},
	    minRange: 1,
	    maxRange: 1,
	    defense: 6,
	    canCapture: true,
	    attackAfterMove: true,
	    moveAfterAttack: 0,
	    repair: 1,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{mountain: [6, 2, 4],
		forest: [4, 2, 3],
		base: [4, 2, 2],
		harbor: [3, 2, 2],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [5, -1, -1],
		bridge: [3, 0, -1],
		road: [3, 0, -1],
		city: [5, -2, -2],
		reef: [6, -2, -3],
		abyss: [6, -3, -4],
		swamp: [6, -1, -2]}
	},
	cyberUnderling: {
            name: 'Cyber-Underling',
	    cost: 100,
	    race: 'titans',
	    cannotBeBuilt: true,
		canPopup: true,
	    mobility: 10,
	    vision: 4,
	    class: 'GL',
	    attack: { GL: 7, GH: 4, AIR: 2, AQUA: 2},
	    minRange: 1,
	    maxRange: 1,
	    defense: 6,
	    canCapture: true,
	    attackAfterMove: true,
	    moveAfterAttack: 0,
	    repair: 1,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{mountain: [6, 2, 4],
		forest: [4, 2, 3],
		base: [4, 2, 2],
		harbor: [3, 2, 2],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [5, -1, -1],
		bridge: [3, 0, -1],
		road: [3, 0, -1],
		city: [5, -2, -2],
		reef: [6, -2, -3],
		abyss: [6, -3, -4],
		swamp: [6, -1, -2]}
	},
	assimilator: {
            name: 'Assimilator',
	    cost: 200,
	    race: 'titans',
	    mobility: 6,
	    vision: 3,
	    class: 'GL',
	    attack: { GL: 0, GH: 0, AIR: 0, AQUA: 0},
	    minRange: 0,
	    maxRange: 0,
	    defense: 0,
	    canCapture: true,
	    attackAfterMove: false,
	    moveAfterAttack: 0,
	    repair: 1,
	    repairBonus: 2,
	    actions: 1,
	    unitConversion: ['underling', 'cyberUnderling'],
	    specialAttack: 'UV',
	    specialAttackRange: 5,
	    specialAttackRecharge: 11,
	    terrain:
		{mountain: [6, 0, 4],
		forest: [4, 0, 3],
		base: [4, 0, 2],
		harbor: [3, 0, 2],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [5, 0, -1],
		bridge: [3, 0, -1],
		road: [3, 0, -1],
		city: [5, -2, -2],
		reef: [6, -2, -3],
		abyss: [6, -3, -4],
		swamp: [6, 0, -2]}
	},
	speeder: {
            name: 'Speeder',
	    cost: 250,
	    race: 'titans',
	    mobility: 16,
	    vision: 5,
	    class: 'GH',
	    attack: { GL: 10, GH: 5, AIR: 5, AQUA: 5},
	    minRange: 1,
	    maxRange: 1,
	    defense: 8,
	    canCapture: false,
	    attackAfterMove: true,
	    moveAfterAttack: 6,
	    repair: 2,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{forest: [6, 0, -3],
		base: [4, 0, -1],
		harbor: [3, 0, -1],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [4, 0, 0],
		bridge: [2, 0, -2],
		road: [2, 0, -2],
		city: [5, -3, -3],
		swamp: [6, -1, -2]}
	},
	plasmaTank: {
            name: 'Plasma Tank',
	    cost: 500,
	    race: 'titans',
	    mobility: 6,
	    vision: 3,
	    class: 'GH',
	    attack: { GL: 10, GH: 11, AIR: 5, AQUA: 11},
	    minRange: 1,
	    maxRange: 1,
	    defense: 14,
	    canCapture: false,
	    attackAfterMove: true,
	    moveAfterAttack: 0,
	    repair: 1,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{forest: [6, 0, -3],
		base: [4, 0, -1],
		harbor: [3, 0, -1],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [4, 0, 0],
		bridge: [2, 0, -2],
		road: [2, 0, -2],
		city: [5, -3, -3],
		swamp: [6, -1, -2]}
	},
	eclipse: {
            name: 'Eclipse',
	    cost: 400,
	    race: 'titans',
	    mobility: 10,
	    vision: 4,
	    class: 'GH',
	    attack: { GL: 10, GH: 4, AIR: 12, AQUA: 9},
	    minRange: 1,
	    maxRange: 2,
	    defense: 9,
	    canCapture: false,
	    attackAfterMove: true,
	    moveAfterAttack: 0,
	    repair: 1,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{forest: [6, 0, -3],
		base: [4, 0, -1],
		harbor: [3, 0, -1],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [4, 0, 0],
		bridge: [2, 0, -2],
		road: [2, 0, -2],
		city: [5, -3, -3],
		swamp: [6, -1, -2]}
	},
	walker: {
            name: 'Walker',
	    cost: 750,
	    race: 'titans',
	    mobility: 6,
	    vision: 5,
	    class: 'GH',
	    attack: { GL: 10, GH: 10, AIR: 11, AQUA: 10},
	    minRange: 3,
	    maxRange: 5,
	    defense: 5,
	    canCapture: false,
	    attackAfterMove: false,
	    moveAfterAttack: 0,
	    repair: 1,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{forest: [6, 0, -3],
		base: [4, 0, -1],
		harbor: [3, 0, -1],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [4, 0, 0],
		bridge: [2, 0, -2],
		road: [2, 0, -2],
		city: [5, -3, -3],
		swamp: [6, -1, -2]}
	},
	hydronaut: {
            name: 'Hydronaut',
	    cost: 800,
	    race: 'titans',
	    mobility: 11,
	    vision: 6,
	    class: 'AQUA',
	    attack: { GL: 12, GH: 10, AIR: 12, AQUA: 13},
	    minRange: 2,
	    maxRange: 4,
	    defense: 10,
	    canCapture: false,
	    attackAfterMove: true,
	    moveAfterAttack: 0,
	    repair: 2,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{water: [3, 0, 0],
		bridge: [4, 0, -2],
		reef: [5, -3, -4],
		ocean: [3, 0, 0],
		harbor: [3, 0, -1]}
	},
	underling: {
            name: 'Underling',
	    cost: 100,
	    race: 'khraleans',
	    mobility: 11,
	    vision: 3,
	    class: 'GL',
	    attack: { GL: 6, GH: 3, AIR: 0, AQUA: 2},
	    minRange: 1,
	    maxRange: 1,
	    defense: 5,
	    canCapture: true,
		canPopup: true,
	    attackAfterMove: true,
	    moveAfterAttack: 0,
	    repair: 1,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{mountain: [6, 2, 4],
		forest: [4, 2, 3],
		base: [4, 2, 2],
		harbor: [3, 2, 2],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [5, -1, -1],
		bridge: [3, 0, -1],
		road: [3, 0, -1],
		city: [5, -2, -2],
		reef: [6, -2, -3],
		abyss: [6, -3, -4],
		swamp: [6, -1, -2]}
	},
	infectedMarine: {
            name: 'Infected Marine',
	    cost: 100,
	    race: 'khraleans',
	    cannotBeBuilt: true,
	    mobility: 10,
	    vision: 4,
	    class: 'GL',
	    attack: { GL: 7, GH: 4, AIR: 4, AQUA: 2},
	    minRange: 1,
	    maxRange: 1,
	    defense: 6,
	    canCapture: true,
	    attackAfterMove: true,
	    moveAfterAttack: 0,
	    repair: 1,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{mountain: [6, 2, 4],
		forest: [4, 2, 3],
		base: [4, 2, 2],
		harbor: [3, 2, 2],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [5, -1, -1],
		bridge: [3, 0, -1],
		road: [3, 0, -1],
		city: [5, -2, -2],
		reef: [6, -2, -3],
		abyss: [6, -3, -4],
		swamp: [6, -1, -2]}
	},
	infector: {
            name: 'Infector',
	    cost: 300,
	    race: 'khraleans',
	    mobility: 8,
	    vision: 3,
	    class: 'GL',
	    attack: { GL: 0, GH: 0, AIR: 0, AQUA: 0},
	    minRange: 0,
	    maxRange: 0,
	    defense: 0,
	    canCapture: true,
	    attackAfterMove: false,
	    moveAfterAttack: 0,
	    repair: 1,
	    repairBonus: 3,
	    actions: 1,
	    unitConversion: ['marine', 'infectedMarine'],
	    specialAttack: 'Plague',
	    specialAttackRange: 2,
	    specialAttackRecharge: 0,
	    terrain:
		{mountain: [6, 0, 4],
		forest: [4, 0, 3],
		base: [4, 0, 2],
		harbor: [3, 0, 2],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [5, 0, -1],
		bridge: [3, 0, -1],
		road: [3, 0, -1],
		city: [5, -2, -2],
		reef: [6, -2, -3],
		abyss: [6, -3, -4],
		swamp: [6, 0, -2]}
	},
	swarmer: {
            name: 'Swarmer',
	    cost: 250,
	    race: 'khraleans',
	    mobility: 9,
	    vision: 5,
	    class: 'AIR',
	    attack: { GL: 7, GH: 4, AIR: 3, AQUA: 6},
	    minRange: 1,
	    maxRange: 2,
	    defense: 4,
	    canCapture: false,
	    attackAfterMove: true,
	    moveAfterAttack: 0,
	    repair: 1,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{mountain: [3, 0, 0],
		forest: [3, 0, 0],
		base: [4, 0, 0],
		harbor: [3, 0, 0],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [3, 0, 0],
		swamp: [3, 0, 0],
		bridge: [3, 0, 0],
		road: [3, 0, 0],
		city: [5, -2, -2],
		reef: [3, 0, 0],
		abyss: [4, 0, 0],
		water: [3, 0, 0]}
	},
	garuda: {
            name: 'Garuda',
	    cost: 350,
	    race: 'khraleans',
	    mobility: 12,
	    vision: 5,
	    class: 'AIR',
	    attack: { GL: 7, GH: 8, AIR: 9, AQUA: 9},
	    minRange: 1,
	    maxRange: 1,
	    defense: 8,
	    canCapture: false,
	    attackAfterMove: true,
	    moveAfterAttack: 0,
	    repair: 2,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{mountain: [3, 0, 0],
		forest: [3, 0, 0],
		base: [4, 0, 0],
		harbor: [3, 0, 0],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [3, 0, 0],
		bridge: [3, 0, 0],
		road: [3, 0, 0],
		city: [5, -2, -2],
		reef: [3, 0, 0],
		abyss: [4, 0, 0],
		swamp: [3, 0, 0],
		water: [3, 0, 0]}
	},
	pinzer: {
            name: 'Pinzer',
	    cost: 450,
	    race: 'khraleans',
	    mobility: 8,
	    vision: 3,
	    class: 'GH',
	    attack: { GL: 12, GH: 10, AIR: 3, AQUA: 10},
	    minRange: 1,
	    maxRange: 1,
	    defense: 13,
	    canCapture: false,
	    attackAfterMove: true,
	    moveAfterAttack: 0,
	    repair: 2,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{forest: [6, 0, -3],
		base: [4, 0, -1],
		harbor: [3, 0, -1],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [4, 0, 0],
		bridge: [2, 0, -2],
		road: [2, 0, -2],
		city: [5, -3, -3],
		swamp: [6, -1, -2]}
	},
	wyrm: {
            name: 'Wyrm',
	    cost: 550,
	    race: 'khraleans',
	    mobility: 6,
	    vision: 3,
	    class: 'GH',
	    attack: { GL: 10, GH: 9, AIR: 12, AQUA: 10},
	    minRange: 1,
	    maxRange: 3,
	    defense: 4,
	    canCapture: false,
	    attackAfterMove: true,
	    moveAfterAttack: 0,
	    repair: 1,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{forest: [6, 0, -3],
		base: [4, 0, -1],
		harbor: [3, 0, -1],
		plain: [3, 0, 0],
		medical: [3, 0, 0],
		desert: [4, 0, 0],
		bridge: [2, 0, -2],
		road: [2, 0, -2],
		city: [5, -3, -3],
		swamp: [6, -1, -2]}
	},
	leviathan: {
            name: 'Leviathan',
	    cost: 600,
	    race: 'khraleans',
	    mobility: 11,
	    vision: 4,
	    class: 'AQUA',
	    attack: { GL: 10, GH: 10, AIR: 9, AQUA: 12},
	    minRange: 1,
	    maxRange: 3,
	    defense: 12,
	    canCapture: false,
	    attackAfterMove: true,
	    moveAfterAttack: 0,
	    repair: 2,
	    repairBonus: 0,
	    actions: 1,
	    terrain:
		{water: [3, 0, 0],
		bridge: [4, 0, -2],
		reef: [5, -3, -4],
		ocean: [3, 0, 0],
		harbor: [3, 0, -1]}
	},
    }
}